### ISSUE TITLE
Issue installing Kubeflow 1.3.0 using ArgoFlow

### ISSUE THREAD

**Issue by subramaniankarthik** [kubeflow-onprem/ArgoFlow#11]
I am following the installation process for kubeflow 1.3.0 locally. I have followed all the steps outlined. 

However, when I apply the kubeflow.yaml **kubectl apply -f kubeflow.yaml** 

I get a message saying **application.argoproj.io/kubeflow created**

I don't see a pod running in my namespace, nor do I know if its applying.

Not sure, I am missing something obvious.

Help is appreciated

**Comment by DavidSpek** [comment]
The `kubeflow.yaml` file is an Argo CD application spec. Do you see the kubeflow applications in the Argo CD UI? Also, what namespace are you referring to exactly? As the kubeflow components will run in the `kubeflow` namespace, and some other dependencies run in their own namespace as well, such as istio, dex, knative.

**Comment by subramaniankarthik** [comment]
@DavidSpek , I can see kubeflow in the Argo CD UI, but I cannot see anything else. Refer below screenshot

<img width="851" alt="Screen Shot 2021-04-07 at 10 28 15 AM" src="https://user-images.githubusercontent.com/10652054/113892861-1052a780-978c-11eb-953e-b956bd637f45.png">

Also when I inspect the namespace in my cluster, I see this

<img width="693" alt="Screen Shot 2021-04-07 at 10 31 08 AM" src="https://user-images.githubusercontent.com/10652054/113893228-6f182100-978c-11eb-9711-e05b160cfb38.png">

Not sure, what I am missing

**Comment by DavidSpek** [comment]
@subramaniankarthik If you click on the kubeflow appication in Argo CD. What does it show? It is not creating the application and the state is unknown so something is going wrong the the deployment.

**Comment by subramaniankarthik** [comment]
@DavidSpek , When I click on the kubeflow application in Argo CD, it just takes me to a control page, but it doesnt spin up kubeflow. I have followed all the steps. 

When I run (base) **kubectl get svc istio-ingressgateway -n istio-system** , I get an error saying **Error from server (NotFound): namespaces "istio-system" not found**

Not sure where I am going wrong

**Comment by DavidSpek** [comment]
@subramaniankarthik Yes it should take you to a control page, but it should show information like why it isn't syncing. The Kubeflow component applications aren't being deployed, so nothing has actually been deployed yet.

**Comment by DavidSpek** [comment]
This is what it should look like:
![image](https://user-images.githubusercontent.com/28541758/113907157-5122de80-97d5-11eb-9fa9-4855bd950991.png)

In the top, instead of seeing `Sync OK` you will see some type of error.

**Comment by subramaniankarthik** [comment]
@DavidSpek **rpc error: code = Unknown desc = repository not found**. This is the error I am seeing now in argo.

**Comment by subramaniankarthik** [comment]
@DavidSpek , let me get on that soon

**Comment by DavidSpek** [comment]
Also, the reason the repo isn't found is because the application is pointed to `github.com/3mcloud/aws-data...` and not your fork of the repo.

**Comment by subramaniankarthik** [comment]
@DavidSpek , Got it. I was doing that because I forked the repo and I pushed it into my internal repo

**Comment by DavidSpek** [comment]
@subramaniankarthik Argo CD needs to be able to access the repository. So if it is a private repo you will need to add credentials to Argo CD so it can grab from there.

**Comment by subramaniankarthik** [comment]
@DavidSpek , Got it, now I understand the issue. Let me get this done. Thank you very much

**Comment by DavidSpek** [comment]
@subramaniankarthik Awesome. Please let me know how it goes, both good and bad. Also, as fixes get pushed to the kubeflow components and in this repo you will probably want to keep yours up to date. You can do this by rebasing your change on the upstream (this) repo. 

```
git fetch upstream
git rebase upstream/master
git push origin master --force
```
This assumes you are using the master branch in Argo CD.

**Comment by DavidSpek** [comment]
This issue was caused by Argo CD not being able to access the public repository and also needing to set the `targetRevision` to a specific branch/release of the repository. The README has been updated so it states that Argo CD must be able to access the repository with a link how to add credentials to Argo CD. For the second issue the `setup_repo.sh` script has been extended so that a second argument can be passed which configures the `targetRevision` for all the application specs.

With the above mentioned fixes now implemented I believe this issue can now be closed.
