### ISSUE TITLE
New users not being added to dex static 

### ISSUE THREAD

**Issue by matty1979** [kubeflow-onprem/ArgoFlow#13]
Unable to have new users be added to staticUsers following the given example with the base64 encode.

**Comment by matty1979** [comment]
Instructions need to be updated in README.md 
- update `configmap-patch.yaml`
- [Use bcrypt](https://www.browserling.com/tools/bcrypt)
- Rollout deployment `kubectl rollout restart deployment dex -n auth`

**Comment by DavidSpek** [comment]
Thanks for catching that. I'll update the README in the morning.

**Comment by DavidSpek** [comment]
Sorry it took a bit longer that expected, but I've just added this to the instructions so I'm closing this issue.
